### ISSUE TITLE
Invalid integer issue

### ISSUE THREAD

**Issue by ghorbani-m** [functionland/fula-sec#6]
I am trying to use the fula-sec library on the [fx-fotos](https://github.com/functionland/fx-fotos) react-native mobile application, I just added the package to the project and import it to one of my screens and got this error:

`Error: Invalid integer: 0x10000000000000000000000000000000000000000000000000000000000000000, js engine: hermes`

**Comment by ehsan6sha** [comment]
@Ruffiano We should change the metro.config.js and add the below block to it:
```
transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
```

**Comment by ghorbani-m** [comment]
> @Ruffiano We should change the metro.config.js and add the below block to it:
> 
> ```
> transformer: {
>     getTransformOptions: async () => ({
>       transform: {
>         experimentalImportSupport: false,
>         inlineRequires: true,
>       },
>     }),
>   },
> ```

Thanks @ehsan6sha , It works.

**Comment by Ruffiano** [comment]
This problem was solved in the latest update of fula-sec.
